# Generated by Django 6.0.6 on 2026-07-26 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_requests_donations', '0004_medicalcase_medicaldonation'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
