# Generated by Django 6.0.6 on 2026-07-29 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_requests_donations', '0005_news'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'news', 'verbose_name_plural': 'news'},
        ),
        migrations.AddField(
            model_name='medicalcase',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='medical/'),
        ),
    ]
